package pipeline

import (
	"context"
	"fmt"
	"io"
	"path/filepath"
	"time"

	"github.com/course-creator/core-processor/models"
)

// MockLLMManager is a mock LLM manager for testing
type MockLLMManager struct {
	GeneratedContent map[string]string // prompt -> content
	ShouldFail       map[string]bool   // prompt -> should fail
	CallCount        int
}

// NewMockLLMManager creates a new mock LLM manager
func NewMockLLMManager() *MockLLMManager {
	return &MockLLMManager{
		GeneratedContent: make(map[string]string),
		ShouldFail:       make(map[string]bool),
		CallCount:        0,
	}
}

// GenerateContent generates mock content for testing
func (m *MockLLMManager) GenerateContent(ctx context.Context, prompt string, options map[string]interface{}) (string, error) {
	m.CallCount++

	// Check if this prompt should fail
	if m.ShouldFail[prompt] {
		return "", fmt.Errorf("mock LLM failure for prompt: %s", prompt)
	}

	// Return cached content if already generated
	if content, ok := m.GeneratedContent[prompt]; ok {
		return content, nil
	}

	// Generate mock content based on prompt type
	var content string
	switch {
	case contains(prompt, "lesson"):
		content = `# Mock Lesson Content
This is a mock lesson generated for testing purposes.

## Learning Objectives
- Understand mock testing
- Learn about test helpers
- Practice with mock implementations

## Content
This lesson demonstrates how mock objects work in testing frameworks.`
	case contains(prompt, "diagram"):
		content = `graph TD
    A[Mock Input] --> B{Process}
    B --> C[Mock Output]
    B --> D[Alternative Output]
    
    style A fill:#f9f,stroke:#333,stroke-width:2px
    style C fill:#ccf,stroke:#333,stroke-width:2px`
	case contains(prompt, "summary"):
		content = "Mock summary: This is a test summary generated by the mock LLM."
	default:
		content = fmt.Sprintf("Mock content for prompt: %s (call #%d)", prompt, m.CallCount)
	}

	m.GeneratedContent[prompt] = content
	return content, nil
}

// SetFailure sets a prompt to fail
func (m *MockLLMManager) SetFailure(prompt string) {
	m.ShouldFail[prompt] = true
}

// ClearFailures clears all failure settings
func (m *MockLLMManager) ClearFailures() {
	m.ShouldFail = make(map[string]bool)
}

// GetCallCount returns the number of times GenerateContent was called
func (m *MockLLMManager) GetCallCount() int {
	return m.CallCount
}

// Reset resets the mock state
func (m *MockLLMManager) Reset() {
	m.GeneratedContent = make(map[string]string)
	m.ShouldFail = make(map[string]bool)
	m.CallCount = 0
}

// MockFileStorage is a mock file storage for testing
type MockFileStorage struct {
	Files          map[string][]byte // path -> content
	ShouldFail     map[string]bool   // path -> should fail
	CallCount      int
	ReadCallCount  int
	WriteCallCount int
}

// NewMockFileStorage creates a new mock file storage
func NewMockFileStorage() *MockFileStorage {
	return &MockFileStorage{
		Files:      make(map[string][]byte),
		ShouldFail: make(map[string]bool),
		CallCount:  0,
	}
}

// Save saves mock file content
func (m *MockFileStorage) Save(path string, content []byte) error {
	m.CallCount++
	m.WriteCallCount++

	if m.ShouldFail[path] {
		return fmt.Errorf("mock storage failure for path: %s", path)
	}

	m.Files[path] = content
	return nil
}

// SaveReader saves mock file content from reader
func (m *MockFileStorage) SaveReader(path string, reader io.Reader) error {
	m.CallCount++
	m.WriteCallCount++

	if m.ShouldFail[path] {
		return fmt.Errorf("mock storage failure for path: %s", path)
	}

	content, err := io.ReadAll(reader)
	if err != nil {
		return err
	}

	m.Files[path] = content
	return nil
}

// Load loads mock file content
func (m *MockFileStorage) Load(path string) ([]byte, error) {
	m.CallCount++
	m.ReadCallCount++

	if m.ShouldFail[path] {
		return nil, fmt.Errorf("mock storage failure for path: %s", path)
	}

	content, ok := m.Files[path]
	if !ok {
		return nil, fmt.Errorf("file not found: %s", path)
	}

	return content, nil
}

// Exists checks if mock file exists
func (m *MockFileStorage) Exists(path string) bool {
	m.CallCount++

	if m.ShouldFail[path] {
		return false
	}

	_, ok := m.Files[path]
	return ok
}

// Delete deletes mock file
func (m *MockFileStorage) Delete(path string) error {
	m.CallCount++

	if m.ShouldFail[path] {
		return fmt.Errorf("mock storage failure for path: %s", path)
	}

	delete(m.Files, path)
	return nil
}

// List lists mock files
func (m *MockFileStorage) List(dir string) ([]string, error) {
	m.CallCount++

	var files []string
	for path := range m.Files {
		if dir == "" || len(path) >= len(dir) && path[:len(dir)] == dir {
			files = append(files, path)
		}
	}

	return files, nil
}

// CreateDir creates a mock directory
func (m *MockFileStorage) CreateDir(path string) error {
	m.CallCount++

	if m.ShouldFail[path] {
		return fmt.Errorf("mock storage failure for path: %s", path)
	}

	// For mock storage, we just ensure the path exists in our map
	m.Files[path+"/.keep"] = []byte{}
	return nil
}

// GetURL returns a mock URL for the file
func (m *MockFileStorage) GetURL(path string) string {
	return "http://localhost:8080/storage/" + path
}

// GetSize returns the size of the mock file
func (m *MockFileStorage) GetSize(path string) (int64, error) {
	m.CallCount++

	if m.ShouldFail[path] {
		return 0, fmt.Errorf("mock storage failure for path: %s", path)
	}

	content, ok := m.Files[path]
	if !ok {
		return 0, fmt.Errorf("file not found: %s", path)
	}

	return int64(len(content)), nil
}

// SetFailure sets a path to fail
func (m *MockFileStorage) SetFailure(path string) {
	m.ShouldFail[path] = true
}

// ClearFailures clears all failure settings
func (m *MockFileStorage) ClearFailures() {
	m.ShouldFail = make(map[string]bool)
}

// GetFileContent returns the content of a mock file
func (m *MockFileStorage) GetFileContent(path string) ([]byte, bool) {
	content, ok := m.Files[path]
	return content, ok
}

// Reset resets the mock state
func (m *MockFileStorage) Reset() {
	m.Files = make(map[string][]byte)
	m.ShouldFail = make(map[string]bool)
	m.CallCount = 0
	m.ReadCallCount = 0
	m.WriteCallCount = 0
}

// MockBackgroundGenerator is a mock background generator for testing
type MockBackgroundGenerator struct {
	GeneratedImages map[string]string // theme -> image path
	ShouldFail      map[string]bool   // theme -> should fail
	CallCount       int
}

// NewMockBackgroundGenerator creates a new mock background generator
func NewMockBackgroundGenerator() *MockBackgroundGenerator {
	return &MockBackgroundGenerator{
		GeneratedImages: make(map[string]string),
		ShouldFail:      make(map[string]bool),
		CallCount:       0,
	}
}

// Generate generates mock background image
func (m *MockBackgroundGenerator) Generate(theme string, width, height int) (string, error) {
	m.CallCount++

	if m.ShouldFail[theme] {
		return "", fmt.Errorf("mock background generator failure for theme: %s", theme)
	}

	// Return cached path if already generated
	if path, ok := m.GeneratedImages[theme]; ok {
		return path, nil
	}

	// Generate mock image path
	imagePath := filepath.Join("/tmp/mock_backgrounds", fmt.Sprintf("bg_%s_%d.png", theme, m.CallCount))
	m.GeneratedImages[theme] = imagePath

	return imagePath, nil
}

// SetFailure sets a theme to fail
func (m *MockBackgroundGenerator) SetFailure(theme string) {
	m.ShouldFail[theme] = true
}

// ClearFailures clears all failure settings
func (m *MockBackgroundGenerator) ClearFailures() {
	m.ShouldFail = make(map[string]bool)
}

// Reset resets the mock state
func (m *MockBackgroundGenerator) Reset() {
	m.GeneratedImages = make(map[string]string)
	m.ShouldFail = make(map[string]bool)
	m.CallCount = 0
}

// TestCourseData creates test course data
func TestCourseData() models.Course {
	now := time.Now()
	return models.Course{
		ID:          "test-course-123",
		Title:       "Test Course",
		Description: "A test course for unit testing",
		Lessons: []models.Lesson{
			{
				ID:       "lesson-1",
				Title:    "Introduction to Testing",
				Content:  "# Introduction\n\nThis is a test lesson about unit testing.",
				Duration: 300,
				Order:    1,
			},
		},
		Metadata: models.CourseMetadata{
			Author:        "Test Author",
			Language:      "en",
			Tags:          []string{"test", "mock", "unit-testing"},
			TotalDuration: 300,
		},
		CreatedAt: &now,
		UpdatedAt: &now,
	}
}

// TestProcessingOptions creates test processing options
func TestProcessingOptions() models.ProcessingOptions {
	voice := "en_US-male"
	return models.ProcessingOptions{
		Voice:           &voice,
		BackgroundMusic: false,
		BackgroundStyle: "professional",
		Languages:       []string{"en"},
		Quality:         "high",
	}
}

// TestMarkdownContent creates test markdown content
func TestMarkdownContent() string {
	return `# Test Course

## Course Description
This is a test course for unit testing.

## Learning Objectives
- Understand unit testing concepts
- Learn about mock objects
- Practice test-driven development

## Lesson 1: Introduction to Testing

### What is Unit Testing?
Unit testing is a software testing method where individual units of source code are tested to determine if they are fit for use.

### Why Unit Testing?
- Catch bugs early
- Improve code quality
- Facilitate refactoring

## Lesson 2: Mock Objects

### What are Mocks?
Mock objects simulate the behavior of real objects in controlled ways.

### Benefits of Mocks
- Isolate code under test
- Control test environment
- Speed up tests
`
}

// contains checks if string contains substring
func contains(s, substr string) bool {
	return len(s) >= len(substr) && (s == substr || len(s) > len(substr) && (s[:len(substr)] == substr || contains(s[1:], substr)))
}
